/**
 * Built-in content catalogue.
 *
 * This is the single source of truth for the site in two situations:
 *   1. No Supabase credentials are configured — the site renders from here so
 *      it is fully explorable out of the box (read-only "preview" mode).
 *   2. Seeding a fresh Supabase project — /admin/setup imports this catalogue
 *      into the live database in one click.
 *
 * Prices are in kobo (₦1 = 100 kobo).
 */
import type {
  Announcement,
  Experience,
  GalleryImage,
  MenuSection,
  OpeningHour,
  SiteSettings,
  Testimonial,
  VenueEvent,
} from "./types";

const img = (id: string, w = 1200) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

export const seedSettings: SiteSettings = {
  id: "default",
  brand_name: "Whiskey Mistress",
  tagline: "Luxury Dining · Lounge · Entertainment",
  hero_headline: "Abuja's Premier Luxury Dining & Entertainment Experience",
  hero_subheadline:
    "Experience exceptional cuisine, elegant hospitality, immersive entertainment, and memorable celebrations in a destination designed for every special occasion.",
  about_heading: "An Address For Occasions Worth Remembering",
  about_body:
    "Whiskey Mistress was created for the moments that deserve more than a table — the anniversary, the closing dinner, the birthday that turns into a night. Behind our doors, warm brass light falls across marble, a live set drifts through the lounge, and a team that has spent years in luxury hospitality reads the room before you have to ask.\n\nOur kitchen moves confidently between Nigerian cuisine cooked with real reverence and a modern grill, seafood and pasta programme built on produce we select ourselves. Every plate leaves the pass finished by hand.\n\nBeyond the dining room you will find intimate executive booths, private rooms for celebration and corporate hosting, and VIP lounges where the evening keeps its own time. Whether you arrive for a quiet dinner for two or take the room for eighty, the standard is the same: exceptional food, effortless service, and an atmosphere you will want to return to.",
  about_image_url: img("1552566626-52f8b828add9", 1400),
  address_line: "Plot 1234, Aminu Kano Crescent, Wuse II",
  city: "Abuja",
  country: "Nigeria",
  phone: "+234 800 000 0000",
  whatsapp: "2348000000000",
  email: "reservations@whiskeymistress.com",
  maps_query: "Aminu Kano Crescent, Wuse II, Abuja, Nigeria",
  instagram_url: "https://instagram.com/whiskeymistress",
  facebook_url: "https://facebook.com/whiskeymistress",
  x_url: "https://x.com/whiskeymistress",
  tiktok_url: "https://tiktok.com/@whiskeymistress",
  reservation_lead_time_hours: 3,
  max_party_size: 30,
};

export const seedAnnouncement: Announcement = {
  id: "seed-announcement",
  message: "Sunday Brunch & Live Sax — every Sunday, 1pm till late.",
  link_label: "Reserve",
  link_href: "#reservations",
  starts_at: null,
  ends_at: null,
  is_published: true,
};

/* ----------------------------------------------------------------- dining */

export const seedFoodSections: MenuSection[] = [
  {
    id: "cat-starters",
    kind: "food",
    name: "Starters",
    slug: "starters",
    description: "Small plates built for the first pour of the evening.",
    sort_order: 1,
    is_published: true,
    items: [
      {
        id: "f-1",
        category_id: "cat-starters",
        name: "Peppered Snail Skewers",
        description:
          "Flame-grilled snails, scotch bonnet glaze, charred onion and a squeeze of lime.",
        price_minor: 1850000,
        currency: "NGN",
        image_url: img("1504674900247-0877df9cc836"),
        availability: "available",
        is_signature: true,
        dietary_tags: ["spicy"],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "f-2",
        category_id: "cat-starters",
        name: "Truffle Suya Arancini",
        description:
          "Crisp risotto spheres, smoked suya spice, black truffle aioli.",
        price_minor: 1450000,
        currency: "NGN",
        image_url: img("1541592106381-b31e9677c0e5"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegetarian"],
        sort_order: 2,
        is_published: true,
      },
      {
        id: "f-3",
        category_id: "cat-starters",
        name: "Yaji Calamari",
        description:
          "Lightly battered calamari, yaji dust, burnt lemon crème fraîche.",
        price_minor: 1650000,
        currency: "NGN",
        image_url: img("1599487488170-d11ec9c172f0"),
        availability: "available",
        is_signature: false,
        dietary_tags: [],
        sort_order: 3,
        is_published: true,
      },
      {
        id: "f-4",
        category_id: "cat-starters",
        name: "Beef Short Rib Sliders",
        description:
          "Twelve-hour braised short rib, smoked gouda, brioche, house pickles.",
        price_minor: 1950000,
        currency: "NGN",
        image_url: img("1550547660-d9450f859349"),
        availability: "limited",
        is_signature: false,
        dietary_tags: [],
        sort_order: 4,
        is_published: true,
      },
    ],
  },
  {
    id: "cat-nigerian",
    kind: "food",
    name: "Nigerian Cuisine",
    slug: "nigerian-cuisine",
    description:
      "The classics, cooked with patience and served without shortcuts.",
    sort_order: 2,
    is_published: true,
    items: [
      {
        id: "f-5",
        category_id: "cat-nigerian",
        name: "Native Jollof & Smoked Turkey",
        description:
          "Firewood-finished palm oil jollof, smoked turkey, dried fish, ugu.",
        price_minor: 2250000,
        currency: "NGN",
        image_url: img("1604909052743-94e838986d24"),
        availability: "available",
        is_signature: true,
        dietary_tags: [],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "f-6",
        category_id: "cat-nigerian",
        name: "Seafood Okra & Pounded Yam",
        description:
          "Prawns, snail and croaker in a rich okra, hand-pounded yam.",
        price_minor: 2650000,
        currency: "NGN",
        image_url: img("1567620905732-2d1ec7ab7445"),
        availability: "available",
        is_signature: true,
        dietary_tags: [],
        sort_order: 2,
        is_published: true,
      },
      {
        id: "f-7",
        category_id: "cat-nigerian",
        name: "Egusi Royale",
        description:
          "Melon seed stew with assorted meat and stockfish, choice of swallow.",
        price_minor: 2150000,
        currency: "NGN",
        image_url: img("1596797038530-2c107229654b"),
        availability: "available",
        is_signature: false,
        dietary_tags: [],
        sort_order: 3,
        is_published: true,
      },
      {
        id: "f-8",
        category_id: "cat-nigerian",
        name: "Asun & Plantain",
        description:
          "Peppered goat meat, sweet fried plantain, roasted pepper relish.",
        price_minor: 1950000,
        currency: "NGN",
        image_url: img("1606787366850-de6330128bfc"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["spicy"],
        sort_order: 4,
        is_published: true,
      },
    ],
  },
  {
    id: "cat-grills",
    kind: "food",
    name: "Grills",
    slug: "grills",
    description: "Open flame, aged cuts, finished at the pass.",
    sort_order: 3,
    is_published: true,
    items: [
      {
        id: "f-9",
        category_id: "cat-grills",
        name: "Tomahawk For Two",
        description:
          "1.2kg dry-aged tomahawk, bone marrow butter, triple-cooked chips.",
        price_minor: 9500000,
        currency: "NGN",
        image_url: img("1600891964092-4316c288032e"),
        availability: "limited",
        is_signature: true,
        dietary_tags: [],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "f-10",
        category_id: "cat-grills",
        name: "Ribeye & Peppercorn",
        description:
          "300g ribeye, green peppercorn sauce, grilled tenderstem.",
        price_minor: 4850000,
        currency: "NGN",
        image_url: img("1546964124-0cce460f38ef"),
        availability: "available",
        is_signature: false,
        dietary_tags: [],
        sort_order: 2,
        is_published: true,
      },
      {
        id: "f-11",
        category_id: "cat-grills",
        name: "Suya-Spiced Lamb Chops",
        description: "Char-grilled lamb rack, yaji crust, mint and onion salad.",
        price_minor: 3950000,
        currency: "NGN",
        image_url: img("1544025162-d76694265947"),
        availability: "available",
        is_signature: true,
        dietary_tags: ["spicy"],
        sort_order: 3,
        is_published: true,
      },
      {
        id: "f-12",
        category_id: "cat-grills",
        name: "Whole Peppered Chicken",
        description:
          "Spatchcocked and slow-grilled, scotch bonnet marinade, jollof rice.",
        price_minor: 2450000,
        currency: "NGN",
        image_url: img("1598103442097-8b74394b95c6"),
        availability: "available",
        is_signature: false,
        dietary_tags: [],
        sort_order: 4,
        is_published: true,
      },
    ],
  },
  {
    id: "cat-seafood",
    kind: "food",
    name: "Seafood",
    slug: "seafood",
    description: "Selected daily, cooked simply.",
    sort_order: 4,
    is_published: true,
    items: [
      {
        id: "f-13",
        category_id: "cat-seafood",
        name: "Grilled Whole Croaker",
        description:
          "Market croaker, peppered marinade, roast potatoes, dodo.",
        price_minor: 3250000,
        currency: "NGN",
        image_url: img("1519708227418-c8fd9a32b7a2"),
        availability: "available",
        is_signature: true,
        dietary_tags: [],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "f-14",
        category_id: "cat-seafood",
        name: "Garlic Butter Tiger Prawns",
        description: "Jumbo prawns, chilli garlic butter, toasted sourdough.",
        price_minor: 3850000,
        currency: "NGN",
        image_url: img("1565299624946-b28f40a0ae38"),
        availability: "available",
        is_signature: false,
        dietary_tags: [],
        sort_order: 2,
        is_published: true,
      },
      {
        id: "f-15",
        category_id: "cat-seafood",
        name: "Seared Salmon & Coconut Broth",
        description:
          "Atlantic salmon, coconut-scotch bonnet broth, sautéed greens.",
        price_minor: 3550000,
        currency: "NGN",
        image_url: img("1467003909585-2f8a72700288"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["gluten-free"],
        sort_order: 3,
        is_published: true,
      },
    ],
  },
  {
    id: "cat-burgers",
    kind: "food",
    name: "Burgers",
    slug: "burgers",
    description: "Ground in house, served with triple-cooked chips.",
    sort_order: 5,
    is_published: true,
    items: [
      {
        id: "f-16",
        category_id: "cat-burgers",
        name: "The Mistress Burger",
        description:
          "Double beef patty, smoked cheddar, bacon jam, truffle mayo.",
        price_minor: 2250000,
        currency: "NGN",
        image_url: img("1568901346375-23c9450c58cd"),
        availability: "available",
        is_signature: true,
        dietary_tags: [],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "f-17",
        category_id: "cat-burgers",
        name: "Suya Chicken Burger",
        description:
          "Buttermilk chicken thigh, yaji spice, slaw, scotch bonnet aioli.",
        price_minor: 1950000,
        currency: "NGN",
        image_url: img("1606755962773-d324e0a13086"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["spicy"],
        sort_order: 2,
        is_published: true,
      },
      {
        id: "f-18",
        category_id: "cat-burgers",
        name: "Garden Halloumi Burger",
        description:
          "Grilled halloumi, roast pepper, rocket, harissa yoghurt.",
        price_minor: 1750000,
        currency: "NGN",
        image_url: img("1571091718767-18b5b1457add"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegetarian"],
        sort_order: 3,
        is_published: true,
      },
    ],
  },
  {
    id: "cat-pizza",
    kind: "food",
    name: "Pizza",
    slug: "pizza",
    description: "48-hour fermented dough, stone baked.",
    sort_order: 6,
    is_published: true,
    items: [
      {
        id: "f-19",
        category_id: "cat-pizza",
        name: "Suya Steak Pizza",
        description:
          "Sliced sirloin, red onion, yaji, mozzarella, coriander oil.",
        price_minor: 2450000,
        currency: "NGN",
        image_url: img("1513104890138-7c749659a591"),
        availability: "available",
        is_signature: true,
        dietary_tags: ["spicy"],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "f-20",
        category_id: "cat-pizza",
        name: "Tartufo Bianca",
        description: "White base, wild mushroom, truffle oil, fior di latte.",
        price_minor: 2650000,
        currency: "NGN",
        image_url: img("1595854341625-f33ee10dbf94"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegetarian"],
        sort_order: 2,
        is_published: true,
      },
      {
        id: "f-21",
        category_id: "cat-pizza",
        name: "Margherita Classica",
        description: "San Marzano, buffalo mozzarella, basil, olive oil.",
        price_minor: 1850000,
        currency: "NGN",
        image_url: img("1604382354936-07c5d9983bd3"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegetarian"],
        sort_order: 3,
        is_published: true,
      },
    ],
  },
  {
    id: "cat-pasta",
    kind: "food",
    name: "Pasta",
    slug: "pasta",
    description: "Rolled and cut daily.",
    sort_order: 7,
    is_published: true,
    items: [
      {
        id: "f-22",
        category_id: "cat-pasta",
        name: "Seafood Linguine",
        description: "Prawns, clams, calamari, chilli, white wine, parsley.",
        price_minor: 3150000,
        currency: "NGN",
        image_url: img("1621996346565-e3dbc353d2e5"),
        availability: "available",
        is_signature: true,
        dietary_tags: [],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "f-23",
        category_id: "cat-pasta",
        name: "Short Rib Pappardelle",
        description: "Slow-braised short rib ragù, aged parmesan.",
        price_minor: 2950000,
        currency: "NGN",
        image_url: img("1551183053-bf91a1d81141"),
        availability: "available",
        is_signature: false,
        dietary_tags: [],
        sort_order: 2,
        is_published: true,
      },
      {
        id: "f-24",
        category_id: "cat-pasta",
        name: "Truffle Tagliatelle",
        description: "Wild mushroom, cream, black truffle, chive.",
        price_minor: 2750000,
        currency: "NGN",
        image_url: img("1473093295043-cdd812d0e601"),
        availability: "seasonal",
        is_signature: false,
        dietary_tags: ["vegetarian"],
        sort_order: 3,
        is_published: true,
      },
    ],
  },
  {
    id: "cat-salads",
    kind: "food",
    name: "Salads",
    slug: "salads",
    description: "Bright, generous, never an afterthought.",
    sort_order: 8,
    is_published: true,
    items: [
      {
        id: "f-25",
        category_id: "cat-salads",
        name: "Grilled Chicken Caesar",
        description:
          "Baby gem, aged parmesan, sourdough croutons, classic dressing.",
        price_minor: 1650000,
        currency: "NGN",
        image_url: img("1546793665-c74683f339c1"),
        availability: "available",
        is_signature: false,
        dietary_tags: [],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "f-26",
        category_id: "cat-salads",
        name: "Avocado & Citrus",
        description: "Avocado, orange, radish, toasted seeds, lime dressing.",
        price_minor: 1450000,
        currency: "NGN",
        image_url: img("1512621776951-a57141f2eefd"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegan", "gluten-free"],
        sort_order: 2,
        is_published: true,
      },
    ],
  },
  {
    id: "cat-desserts",
    kind: "food",
    name: "Desserts",
    slug: "desserts",
    description: "The last word of the evening.",
    sort_order: 9,
    is_published: true,
    items: [
      {
        id: "f-27",
        category_id: "cat-desserts",
        name: "Whiskey Salted Caramel Tart",
        description:
          "Dark chocolate ganache, whiskey caramel, crème fraîche ice cream.",
        price_minor: 1450000,
        currency: "NGN",
        image_url: img("1551024506-0bccd828d307"),
        availability: "available",
        is_signature: true,
        dietary_tags: ["vegetarian"],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "f-28",
        category_id: "cat-desserts",
        name: "Chin Chin Cheesecake",
        description: "Baked vanilla cheesecake, chin chin crumb, mango coulis.",
        price_minor: 1350000,
        currency: "NGN",
        image_url: img("1567171466295-4afa63d45416"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegetarian"],
        sort_order: 2,
        is_published: true,
      },
      {
        id: "f-29",
        category_id: "cat-desserts",
        name: "Puff Puff & Chocolate",
        description: "Warm puff puff, dark chocolate sauce, vanilla bean cream.",
        price_minor: 1150000,
        currency: "NGN",
        image_url: img("1488477181946-6428a0291777"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegetarian"],
        sort_order: 3,
        is_published: true,
      },
    ],
  },
];

/* --------------------------------------------------------------- beverages */

export const seedBeverageSections: MenuSection[] = [
  {
    id: "cat-cocktails",
    kind: "beverage",
    name: "Cocktails",
    slug: "cocktails",
    description: "Built at the bar, garnished to order.",
    sort_order: 1,
    is_published: true,
    items: [
      {
        id: "b-1",
        category_id: "cat-cocktails",
        name: "The Mistress",
        description:
          "House blend, smoked honey, bitters, orange oils — served over a single ice block.",
        price_minor: 1650000,
        currency: "NGN",
        image_url: img("1514362545857-3bc16c4c7d1b"),
        availability: "available",
        is_signature: true,
        dietary_tags: [],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "b-2",
        category_id: "cat-cocktails",
        name: "Hibiscus Sour",
        description: "Zobo reduction, citrus, aromatic foam.",
        price_minor: 1450000,
        currency: "NGN",
        image_url: img("1536935338788-846bb9981813"),
        availability: "available",
        is_signature: false,
        dietary_tags: [],
        sort_order: 2,
        is_published: true,
      },
      {
        id: "b-3",
        category_id: "cat-cocktails",
        name: "Smoked Old Fashioned",
        description: "Barrel-aged, demerara, oak smoke under glass.",
        price_minor: 1850000,
        currency: "NGN",
        image_url: img("1470337458703-46ad1756a187"),
        availability: "available",
        is_signature: true,
        dietary_tags: [],
        sort_order: 3,
        is_published: true,
      },
      {
        id: "b-4",
        category_id: "cat-cocktails",
        name: "Tamarind Margarita",
        description: "Tamarind, lime, agave, chilli salt rim.",
        price_minor: 1550000,
        currency: "NGN",
        image_url: img("1541546006121-5c3bc5e8c7b9"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["spicy"],
        sort_order: 4,
        is_published: true,
      },
    ],
  },
  {
    id: "cat-mocktails",
    kind: "beverage",
    name: "Mocktails",
    slug: "mocktails",
    description: "Zero proof, full character.",
    sort_order: 2,
    is_published: true,
    items: [
      {
        id: "b-5",
        category_id: "cat-mocktails",
        name: "Virgin Zobo Spritz",
        description: "Hibiscus, ginger, citrus, soda.",
        price_minor: 850000,
        currency: "NGN",
        image_url: img("1497534446932-c925b458314e"),
        availability: "available",
        is_signature: true,
        dietary_tags: ["vegan"],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "b-6",
        category_id: "cat-mocktails",
        name: "Cucumber & Mint Cooler",
        description: "Pressed cucumber, mint, lime, tonic.",
        price_minor: 800000,
        currency: "NGN",
        image_url: img("1544145945-f90425340c7e"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegan"],
        sort_order: 2,
        is_published: true,
      },
      {
        id: "b-7",
        category_id: "cat-mocktails",
        name: "Passion & Ginger Fizz",
        description: "Passion fruit, ginger beer, lime.",
        price_minor: 850000,
        currency: "NGN",
        image_url: img("1621263764928-df1444c5e859"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegan"],
        sort_order: 3,
        is_published: true,
      },
    ],
  },
  {
    id: "cat-juices",
    kind: "beverage",
    name: "Fresh Juices",
    slug: "fresh-juices",
    description: "Pressed to order.",
    sort_order: 3,
    is_published: true,
    items: [
      {
        id: "b-8",
        category_id: "cat-juices",
        name: "Cold-Pressed Pineapple & Ginger",
        description: "Pineapple, ginger, a touch of lime.",
        price_minor: 650000,
        currency: "NGN",
        image_url: img("1600271886742-f049cd451bba"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegan"],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "b-9",
        category_id: "cat-juices",
        name: "Watermelon & Mint",
        description: "Pressed watermelon, mint leaf.",
        price_minor: 600000,
        currency: "NGN",
        image_url: img("1622597467836-f3285f2131b8"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegan"],
        sort_order: 2,
        is_published: true,
      },
      {
        id: "b-10",
        category_id: "cat-juices",
        name: "Orange & Turmeric",
        description: "Orange, turmeric, black pepper.",
        price_minor: 650000,
        currency: "NGN",
        image_url: img("1613478223719-2ab802602423"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegan"],
        sort_order: 3,
        is_published: true,
      },
    ],
  },
  {
    id: "cat-softs",
    kind: "beverage",
    name: "Soft Drinks",
    slug: "soft-drinks",
    description: "Chilled and served with citrus.",
    sort_order: 4,
    is_published: true,
    items: [
      {
        id: "b-11",
        category_id: "cat-softs",
        name: "Classic Sodas",
        description: "Coke, Coke Zero, Fanta, Sprite.",
        price_minor: 250000,
        currency: "NGN",
        image_url: img("1581006852262-e4307cf6283a"),
        availability: "available",
        is_signature: false,
        dietary_tags: [],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "b-12",
        category_id: "cat-softs",
        name: "Chapman",
        description: "House Chapman, cucumber, orange, bitters.",
        price_minor: 550000,
        currency: "NGN",
        image_url: img("1595981267035-7b04ca84a82d"),
        availability: "available",
        is_signature: true,
        dietary_tags: [],
        sort_order: 2,
        is_published: true,
      },
      {
        id: "b-13",
        category_id: "cat-softs",
        name: "Premium Tonics",
        description: "Indian, Mediterranean, elderflower.",
        price_minor: 450000,
        currency: "NGN",
        image_url: img("1600271772470-bd22a42787b3"),
        availability: "available",
        is_signature: false,
        dietary_tags: [],
        sort_order: 3,
        is_published: true,
      },
    ],
  },
  {
    id: "cat-coffee",
    kind: "beverage",
    name: "Coffee",
    slug: "coffee",
    description: "Single-origin beans, roasted for us.",
    sort_order: 5,
    is_published: true,
    items: [
      {
        id: "b-14",
        category_id: "cat-coffee",
        name: "Espresso / Double",
        description: "House single origin.",
        price_minor: 400000,
        currency: "NGN",
        image_url: img("1510591509098-f4fdc6d0ff04"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegan"],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "b-15",
        category_id: "cat-coffee",
        name: "Flat White",
        description: "Double ristretto, steamed milk.",
        price_minor: 550000,
        currency: "NGN",
        image_url: img("1541167760496-1628856ab772"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegetarian"],
        sort_order: 2,
        is_published: true,
      },
      {
        id: "b-16",
        category_id: "cat-coffee",
        name: "Affogato",
        description: "Vanilla bean ice cream, hot espresso.",
        price_minor: 750000,
        currency: "NGN",
        image_url: img("1517701550927-30cf4ba1dba5"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegetarian"],
        sort_order: 3,
        is_published: true,
      },
    ],
  },
  {
    id: "cat-tea",
    kind: "beverage",
    name: "Tea",
    slug: "tea",
    description: "Loose leaf, served by the pot.",
    sort_order: 6,
    is_published: true,
    items: [
      {
        id: "b-17",
        category_id: "cat-tea",
        name: "Moroccan Mint",
        description: "Green tea, fresh mint.",
        price_minor: 450000,
        currency: "NGN",
        image_url: img("1544787219-7f47ccb76574"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegan"],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "b-18",
        category_id: "cat-tea",
        name: "Ginger & Lemongrass",
        description: "Caffeine free, honey on the side.",
        price_minor: 450000,
        currency: "NGN",
        image_url: img("1597318181409-cf64d0b5d8a2"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegan"],
        sort_order: 2,
        is_published: true,
      },
    ],
  },
  {
    id: "cat-water",
    kind: "beverage",
    name: "Water",
    slug: "water",
    description: null,
    sort_order: 7,
    is_published: true,
    items: [
      {
        id: "b-19",
        category_id: "cat-water",
        name: "Still Water",
        description: "500ml / 750ml.",
        price_minor: 200000,
        currency: "NGN",
        image_url: img("1548839140-29a749e1cf4d"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegan"],
        sort_order: 1,
        is_published: true,
      },
      {
        id: "b-20",
        category_id: "cat-water",
        name: "Sparkling Water",
        description: "500ml / 750ml.",
        price_minor: 300000,
        currency: "NGN",
        image_url: img("1523362628745-0c100150b504"),
        availability: "available",
        is_signature: false,
        dietary_tags: ["vegan"],
        sort_order: 2,
        is_published: true,
      },
    ],
  },
];

/* ------------------------------------------------------------- experiences */

export const seedExperiences: Experience[] = [
  {
    id: "x-1",
    title: "VIP Lounges",
    description:
      "Elevated, screened seating with a dedicated host, priority service and your own sound. The best seat in the room, all night.",
    image_url: img("1566417713940-fe7c737a9ef2"),
    capacity: "6 – 12 guests",
    price_note: "Minimum spend applies",
    cta_label: "Reserve a Lounge",
    sort_order: 1,
    is_published: true,
  },
  {
    id: "x-2",
    title: "Private Dining",
    description:
      "A separate room, a set menu built with our head chef, and a service team assigned to your table alone.",
    image_url: img("1600891964599-f61ba0e24092"),
    capacity: "8 – 24 guests",
    price_note: "Set menus from ₦45,000 per guest",
    cta_label: "Plan a Dinner",
    sort_order: 2,
    is_published: true,
  },
  {
    id: "x-3",
    title: "Birthday Celebrations",
    description:
      "Reserved seating, a cake presentation with sparklers, personalised signage and a photographer on request.",
    image_url: img("1530103862676-de8c9debad1d"),
    capacity: "4 – 60 guests",
    price_note: "Packages available",
    cta_label: "Celebrate With Us",
    sort_order: 3,
    is_published: true,
  },
  {
    id: "x-4",
    title: "Corporate Events",
    description:
      "Discreet hosting for client dinners, board sessions and end-of-year parties, with AV, screens and invoicing handled.",
    image_url: img("1511578314322-379afb476865"),
    capacity: "10 – 120 guests",
    price_note: "Bespoke quotation",
    cta_label: "Request a Proposal",
    sort_order: 4,
    is_published: true,
  },
  {
    id: "x-5",
    title: "Executive Booths",
    description:
      "Intimate, semi-private booths at the edge of the dining room — for the conversation that matters most.",
    image_url: img("1414235077428-338989a2e8c0"),
    capacity: "2 – 6 guests",
    price_note: "Subject to availability",
    cta_label: "Book a Booth",
    sort_order: 5,
    is_published: true,
  },
  {
    id: "x-6",
    title: "Group Reservations",
    description:
      "Large-party seating with pre-orders taken in advance so the kitchen is ready the moment you arrive.",
    image_url: img("1517248135467-4c7edcad34c4"),
    capacity: "12 – 80 guests",
    price_note: "Pre-order required",
    cta_label: "Enquire Now",
    sort_order: 6,
    is_published: true,
  },
];

/* ------------------------------------------------------------------ events */

export const seedEvents: VenueEvent[] = [
  {
    id: "e-1",
    title: "Saturday Night Live Band",
    slug: "saturday-night-live-band",
    description:
      "Our resident eight-piece plays highlife, afrobeats and soul from 10pm. Dinner service runs alongside.",
    banner_url: img("1493225457124-a3eb161ffa5f"),
    event_date: "2026-08-08",
    start_time: "22:00",
    end_time: "02:00",
    ticket_note: "No cover · Reservation recommended",
    is_featured: true,
    is_published: true,
  },
  {
    id: "e-2",
    title: "Sunday Brunch & Sax",
    slug: "sunday-brunch-and-sax",
    description:
      "Bottomless brunch menu with a live saxophonist through the afternoon. Families welcome until 6pm.",
    banner_url: img("1414235077428-338989a2e8c0"),
    event_date: "2026-08-09",
    start_time: "13:00",
    end_time: "19:00",
    ticket_note: "₦35,000 per guest",
    is_featured: true,
    is_published: true,
  },
  {
    id: "e-3",
    title: "Whiskey & Cigar Masterclass",
    slug: "whiskey-and-cigar-masterclass",
    description:
      "A guided tasting through five expressions with our head of bar, paired with a hand-rolled selection on the terrace.",
    banner_url: img("1527281400683-1aae777175f8"),
    event_date: "2026-08-14",
    start_time: "19:30",
    end_time: "22:00",
    ticket_note: "₦75,000 · 20 seats",
    is_featured: false,
    is_published: true,
  },
  {
    id: "e-4",
    title: "Ladies' Night",
    slug: "ladies-night",
    description:
      "Complimentary welcome cocktail before 10pm, guest DJ, and a dedicated lounge for groups.",
    banner_url: img("1470229722913-7ea0a2c8d21c"),
    event_date: "2026-08-20",
    start_time: "20:00",
    end_time: "01:00",
    ticket_note: "Guest list only",
    is_featured: false,
    is_published: true,
  },
  {
    id: "e-5",
    title: "Chef's Table: Six Courses",
    slug: "chefs-table-six-courses",
    description:
      "Twelve seats at the pass for a six-course tasting menu with optional pairings, hosted by our head chef.",
    banner_url: img("1555396273-367ea4eb4db5"),
    event_date: "2026-08-27",
    start_time: "19:00",
    end_time: "22:30",
    ticket_note: "₦120,000 · 12 seats",
    is_featured: true,
    is_published: true,
  },
  {
    id: "e-6",
    title: "Independence Weekend Gala",
    slug: "independence-weekend-gala",
    description:
      "A black-and-gold dress code, a live orchestra set, and a special menu celebrating Nigerian cuisine.",
    banner_url: img("1519671482749-fd09be7ccebf"),
    event_date: "2026-10-01",
    start_time: "20:00",
    end_time: "03:00",
    ticket_note: "Tables from ₦500,000",
    is_featured: false,
    is_published: true,
  },
];

/* ----------------------------------------------------------------- gallery */

export const seedGallery: GalleryImage[] = [
  {
    id: "g-1",
    image_url: img("1517248135467-4c7edcad34c4", 1400),
    alt: "The main dining room set for evening service",
    category: "Interior",
    width: 1400,
    height: 933,
    sort_order: 1,
    is_published: true,
  },
  {
    id: "g-2",
    image_url: img("1514933651103-005eec06c04b", 1400),
    alt: "The bar at golden hour",
    category: "Lounge",
    width: 1400,
    height: 933,
    sort_order: 2,
    is_published: true,
  },
  {
    id: "g-3",
    image_url: img("1600891964092-4316c288032e", 1400),
    alt: "Dry-aged tomahawk finished at the pass",
    category: "Dining",
    width: 1400,
    height: 933,
    sort_order: 3,
    is_published: true,
  },
  {
    id: "g-4",
    image_url: img("1470229722913-7ea0a2c8d21c", 1400),
    alt: "Live band performing to a full room",
    category: "Entertainment",
    width: 1400,
    height: 933,
    sort_order: 4,
    is_published: true,
  },
  {
    id: "g-5",
    image_url: img("1552566626-52f8b828add9", 1400),
    alt: "Warm brass lighting over the private dining table",
    category: "Interior",
    width: 1400,
    height: 933,
    sort_order: 5,
    is_published: true,
  },
  {
    id: "g-6",
    image_url: img("1514362545857-3bc16c4c7d1b", 1400),
    alt: "A signature cocktail garnished at the bar",
    category: "Lounge",
    width: 1400,
    height: 933,
    sort_order: 6,
    is_published: true,
  },
  {
    id: "g-7",
    image_url: img("1530103862676-de8c9debad1d", 1400),
    alt: "A birthday celebration with sparklers",
    category: "Events",
    width: 1400,
    height: 933,
    sort_order: 7,
    is_published: true,
  },
  {
    id: "g-8",
    image_url: img("1544148103-0773bf10d330", 1400),
    alt: "Guests seated in the VIP lounge",
    category: "Lounge",
    width: 1400,
    height: 933,
    sort_order: 8,
    is_published: true,
  },
  {
    id: "g-9",
    image_url: img("1567620905732-2d1ec7ab7445", 1400),
    alt: "A plated seafood course",
    category: "Dining",
    width: 1400,
    height: 933,
    sort_order: 9,
    is_published: true,
  },
  {
    id: "g-10",
    image_url: img("1519671482749-fd09be7ccebf", 1400),
    alt: "The room during a private gala",
    category: "Events",
    width: 1400,
    height: 933,
    sort_order: 10,
    is_published: true,
  },
  {
    id: "g-11",
    image_url: img("1541532713592-79a0317b6b77", 1400),
    alt: "The terrace at dusk",
    category: "Interior",
    width: 1400,
    height: 933,
    sort_order: 11,
    is_published: true,
  },
  {
    id: "g-12",
    image_url: img("1493225457124-a3eb161ffa5f", 1400),
    alt: "A saxophonist during Sunday service",
    category: "Entertainment",
    width: 1400,
    height: 933,
    sort_order: 12,
    is_published: true,
  },
];

/* ------------------------------------------------------------ testimonials */

export const seedTestimonials: Testimonial[] = [
  {
    id: "t-1",
    guest_name: "Adaeze Okonkwo",
    guest_title: "Celebrated a 40th birthday",
    avatar_url: img("1494790108377-be9c29b29330", 200),
    rating: 5,
    quote:
      "We took the private room for thirty and not a single detail slipped. The cake presentation stopped the whole restaurant. My guests are still talking about the seafood okra.",
    sort_order: 1,
    is_published: true,
  },
  {
    id: "t-2",
    guest_name: "Tunde Bakare",
    guest_title: "Managing Partner",
    avatar_url: img("1507003211169-0a1dd7228f2d", 200),
    rating: 5,
    quote:
      "I host clients here almost every month. The service is discreet, the booths are genuinely private, and the kitchen has never once been slow when it mattered.",
    sort_order: 2,
    is_published: true,
  },
  {
    id: "t-3",
    guest_name: "Zainab Ibrahim",
    guest_title: "Regular guest",
    avatar_url: img("1438761681033-6461ffad8d80", 200),
    rating: 5,
    quote:
      "The band on Saturdays is the best in Abuja, but it is the room that keeps me coming — you can still hear the person across the table.",
    sort_order: 3,
    is_published: true,
  },
  {
    id: "t-4",
    guest_name: "Chuka Eze",
    guest_title: "Anniversary dinner",
    avatar_url: img("1500648767791-00dcc994a43e", 200),
    rating: 5,
    quote:
      "They remembered it was our anniversary from a note on the booking form. Dessert arrived written on the plate. That is the difference.",
    sort_order: 4,
    is_published: true,
  },
  {
    id: "t-5",
    guest_name: "Amara Nwosu",
    guest_title: "Corporate end-of-year party",
    avatar_url: img("1534528741775-53994a69daeb", 200),
    rating: 5,
    quote:
      "Eighty people, full AV, a bespoke menu and one invoice. The events team made my job effortless.",
    sort_order: 5,
    is_published: true,
  },
];

/* ------------------------------------------------------------------- hours */

export const seedHours: OpeningHour[] = [
  { id: "h-0", day_of_week: 0, opens_at: "13:00", closes_at: "00:00", note: "Brunch from 1pm", is_closed: false },
  { id: "h-1", day_of_week: 1, opens_at: "16:00", closes_at: "00:00", note: null, is_closed: false },
  { id: "h-2", day_of_week: 2, opens_at: "16:00", closes_at: "00:00", note: null, is_closed: false },
  { id: "h-3", day_of_week: 3, opens_at: "16:00", closes_at: "01:00", note: null, is_closed: false },
  { id: "h-4", day_of_week: 4, opens_at: "16:00", closes_at: "02:00", note: null, is_closed: false },
  { id: "h-5", day_of_week: 5, opens_at: "16:00", closes_at: "03:00", note: "Live DJ from 10pm", is_closed: false },
  { id: "h-6", day_of_week: 6, opens_at: "13:00", closes_at: "03:00", note: "Live band from 10pm", is_closed: false },
];

export const OCCASIONS = [
  "Birthday",
  "Anniversary",
  "Date Night",
  "Business Dinner",
  "Celebration",
  "Casual Dining",
  "Other",
] as const;

export const SEATING_PREFERENCES = [
  "No preference",
  "Main Dining Room",
  "Executive Booth",
  "VIP Lounge",
  "Terrace",
  "Bar Seating",
] as const;

export const EVENT_TYPES = [
  "Birthday Party",
  "Corporate Dinner",
  "Product Launch",
  "Engagement Party",
  "Networking Event",
  "Private Celebration",
  "Other",
] as const;

export const BUDGET_RANGES = [
  "Under ₦1,000,000",
  "₦1,000,000 – ₦3,000,000",
  "₦3,000,000 – ₦7,000,000",
  "₦7,000,000+",
  "Not sure yet",
] as const;
